/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssociationRouteImport } from './routes/association'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ActualitesIndexRouteImport } from './routes/actualites/index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites/$slug'
import { Route as GalerieIndexRouteImport } from './routes/galerie/index'
import { Route as GalerieSlugRouteImport } from './routes/galerie/$slug'
import { Route as RessourcesIndexRouteImport } from './routes/ressources/index'
import { Route as RessourcesSlugRouteImport } from './routes/ressources/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationRoute = AssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieIndexRoute = GalerieIndexRouteImport.update({
  id: '/galerie/',
  path: '/galerie/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieSlugRoute = GalerieSlugRouteImport.update({
  id: '/galerie/$slug',
  path: '/galerie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/ressources/',
  path: '/ressources/',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesSlugRoute = RessourcesSlugRouteImport.update({
  id: '/ressources/$slug',
  path: '/ressources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/inscription': typeof InscriptionRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/galerie/$slug': typeof GalerieSlugRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/galerie/': typeof GalerieIndexRoute
  '/ressources/': typeof RessourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/inscription': typeof InscriptionRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/galerie/$slug': typeof GalerieSlugRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/galerie': typeof GalerieIndexRoute
  '/ressources': typeof RessourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/inscription': typeof InscriptionRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/galerie/$slug': typeof GalerieSlugRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/galerie/': typeof GalerieIndexRoute
  '/ressources/': typeof RessourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/association'
    | '/contact'
    | '/evenements'
    | '/inscription'
    | '/actualites/$slug'
    | '/galerie/$slug'
    | '/ressources/$slug'
    | '/actualites/'
    | '/galerie/'
    | '/ressources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/association'
    | '/contact'
    | '/evenements'
    | '/inscription'
    | '/actualites/$slug'
    | '/galerie/$slug'
    | '/ressources/$slug'
    | '/actualites'
    | '/galerie'
    | '/ressources'
  id:
    | '__root__'
    | '/'
    | '/association'
    | '/contact'
    | '/evenements'
    | '/inscription'
    | '/actualites/$slug'
    | '/galerie/$slug'
    | '/ressources/$slug'
    | '/actualites/'
    | '/galerie/'
    | '/ressources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssociationRoute: typeof AssociationRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  InscriptionRoute: typeof InscriptionRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  GalerieSlugRoute: typeof GalerieSlugRoute
  RessourcesSlugRoute: typeof RessourcesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  GalerieIndexRoute: typeof GalerieIndexRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association': {
      id: '/association'
      path: '/association'
      fullPath: '/association'
      preLoaderRoute: typeof AssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie/': {
      id: '/galerie/'
      path: '/galerie'
      fullPath: '/galerie/'
      preLoaderRoute: typeof GalerieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie/$slug': {
      id: '/galerie/$slug'
      path: '/galerie/$slug'
      fullPath: '/galerie/$slug'
      preLoaderRoute: typeof GalerieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/ressources'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/$slug': {
      id: '/ressources/$slug'
      path: '/ressources/$slug'
      fullPath: '/ressources/$slug'
      preLoaderRoute: typeof RessourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssociationRoute: AssociationRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  InscriptionRoute: InscriptionRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  GalerieSlugRoute: GalerieSlugRoute,
  RessourcesSlugRoute: RessourcesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  GalerieIndexRoute: GalerieIndexRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
